[workspace]
members = [
    "mallubind",
    "malluscript-wasm",
]

[package]
name = "malluscript"
version = "3.0.0"
authors = ["SyS <sreyassreelal@gmail.com>"]
edition = "2018"
build = "build.rs" 
description = "An esoteric scripting language that lets to write computer programs in Malayalam"

[dependencies]
lalrpop-util = "0.20.0"
clap = "2.33"
rustyline = "6.1"
mallubind = { path = "mallubind" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libloading = "0.9.0"

[build-dependencies]
lalrpop = "0.20.0"

[profile.release]
lto = true
