use std::fmt::Formatter;
#[derive(Clone, Debug, PartialEq, PartialOrd)]
pub enum TokenType {
    Declaration,
    Write,
    InputString,
    InputNumber,
    LeftBrace,
    RightBrace,
    RectO,
    RectC,
    If,
    Else,
    Loop,
    Assignment,
    Plus,
    Minus,
    Product,
    Divide,
    Modulo,
    GreaterThan,
    LessThan,
    EqualTo,
    NotEqual,
    SemiColon,
    OpenParantheses,
    CloseParantheses,
    Um,
    Nekal,
    Function,
    Comma,
    Literal(usize),
    Integer(i64),
    Float(f64),
    Symbol(usize),
}

impl std::fmt::Display for TokenType {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            TokenType::Declaration => write!(f, "pwoli_sadhanam"),
            TokenType::Write => write!(f, "dhe_pidicho"),
            TokenType::InputString => write!(f, "address_thada"),
            TokenType::InputNumber => write!(f, "number_thada"),
            TokenType::LeftBrace => write!(f, "{{"),
            TokenType::RightBrace => write!(f, "}}"),
            TokenType::If => write!(f, "seriyano_mwone"),
            TokenType::Else => write!(f, "seri_allel"),
            TokenType::Loop => write!(f, "repeat_adi"),
            TokenType::Assignment => write!(f, "="),
            TokenType::Plus => write!(f, "+"),
            TokenType::Minus => write!(f, "-"),
            TokenType::Product => write!(f, "*"),
            TokenType::Divide => write!(f, "/"),
            TokenType::Modulo => write!(f, "%"),
            TokenType::GreaterThan => write!(f, "veluthane"),
            TokenType::LessThan => write!(f, "cheruthane"),
            TokenType::EqualTo => write!(f, "same_aane"),
            TokenType::NotEqual => write!(f, "same_alle"),
            TokenType::SemiColon => write!(f, ";"),
            TokenType::OpenParantheses => write!(f, "("),
            TokenType::CloseParantheses => write!(f, ")"),
            TokenType::Um => write!(f, "um"),
            TokenType::Nekal => write!(f, "ne_kal"),
            TokenType::Literal(literal) => write!(f, "{}", literal),
            TokenType::Integer(number) => write!(f, "{}", number),
            TokenType::Float(number) => write!(f, "{}", number),
            TokenType::Symbol(symbol) => write!(f, "{}", symbol),
            TokenType::Function => write!(f, "function"),
            TokenType::Comma => write!(f, ","),
            TokenType::RectO => write!(f, "["),
            TokenType::RectC => write!(f, "]"),
        }
    }
}
